project:
  type: website

website:
  title: "Proj. IDF Brasil ANA/UnB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: "Documentos"
        menu:
          - href: distr_chuva_intensa.qmd
            text: Modelagem probabilística de chuvas intensas
          - href: IDF_basico.qmd 
            text: IDF básico
          - href: desagregacao_temporal.qmd
            text: Desagregacao temporal
          - href: regionalizacao.qmd
            text: Modelos Regionais
          - href: IDF_mudanca.qmd
            text: IDF e as mudanças do clima
          - href: guidelines.qmd
            text: Exemplos de esudos de caráter nacional
          - href: Australia.qmd
            text: Austrália
          - href: Canada.qmd
            text: Canadá
          - href: Inglaterra.qmd
            text: Inglaterra
          - href: estados unidos.qmd
            text: Estados Unidos
            
      #- text: "Tutoriais"
      #  menu: 
      #    - href: tutorial/rs_subdaily_read_hdf_all.qmd
      #      text: Leitura de arquivo hdf
      - href: Blog/index.qmd
        text: Blog
      - href: links.qmd
        text: links

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    lang: pt

editor: visual

