project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    # - "!script_descricao_subdiario.qmd"
    # - "!script_leitura_subdiario.qmd"
    # - "!script_imax_subdiario.qmd"

website:
  title: "Proj. IDF Brasil ANA/UnB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: "Scripts"
        menu: 
          - href: script_leitura_subdiario.qmd
            text: Leitura das séries de precipitação subdiária
          - href: script_descricao_subdiario.qmd
            text: Análise e descrição dos subdiários
          - href: script_imax_subdiario.qmd vss
            text: Geração das intensidades máximas anuais
      - text: "Revisão Bibliográfica"
        menu:
          - href: distr_chuva_intensa.qmd
            text: Modelagem probabilística de chuvas intensas
          - href: desagregacao_temporal.qmd
            text: Desagregacao temporal
          - href: regionalizacao.qmd
            text: Regionalização
          - href: Sensoriamento_remoto.qmd
            text: Sensoriamento remoto
          - href: climate_models.qmd
            text: IDF e as mudanças do clima
          - href: guidelines.qmd
            text: Exemplos de esudos de caráter nacional
          
      #- text: "Tutoriais"
      #  menu: 
      #    - href: tutorial/rs_subdaily_read_hdf_all.qmd
      #      text: Leitura de arquivo hdf
      - href: Blog/index.qmd
        text: Blog
      - href: links.qmd
        text: links

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    lang: pt

editor: visual

execute:
  freeze: auto
  
