---
title: "Desenvolvimento de Curvas Intensidade-Duração-Frequência para o Território Nacional sob a Influência de Mudanças Climáticas"
subtitle: "Componente 1 do projeto Riscos de eventos extremos: drenagem urbana e monitoramento hidrológico SWOT"
---

## Equipe:

### Professores

-   Dirceu S. Reis Jr. (Supervisor acadêmico, Professor UnB)
-   Carlos Henrique Ribeiro Lima (Professor UnB)
-   Cristiano das Neves Almeida (Professor, UFPB)

### Pesquisadores bolsistas do projeto

-   Bruno Silva Pereira (Pesquisador doutor colaborador, PTARH/UnB)
-   Daniele Feitoza Silva (Pesquisadora doutora colaboradora, PTARH/UnB)
-   Filipe Carvalho Lemos (Pesquisador, UFPB)
-   Larissa Zaira Rafael Rolim (Pesquisadora doutora colaboradora, PTARH/UnB)

### Alunos

-   Bruna Dias Silva (Aluna de doutorado do IG/UnB)
-   Eduardo de Queiroz Nascimento (aluno de graduação da UnB)
-   Jonnatha Teixeira Valerio (aluno de graduação da UnB)
-   Tomás Antonio Quezado Duval (Aluno de mestrado do PTARH/UnB)

### Colaboradores

-   Alain de Gois Barbosa (Pesquisador, UFMG)
-   Christian Chadwick (Professor, Universidad Adolfo Ibáñez, Chile)
-   Emerson Freitas da Silva (Pesquisador, UFPB)
-   Luna Gripp Simões Alves (Pesquisadora: estágio pós-doutoral, UFMG)
-   Veber Afonso Figueiredo Costa (Professor, UFMG)

### 
