---
title: "Meta 10 - IDFs para Projeções Futuras"
bibliography:  referencias/ref_meta3.bib
---

De maneira similar às IDFs geradas para cada ponto da grade desenvolvida para os dados históricos/presente, descrito na meta 9, serão desenvolvidas às curvas IDFs para as projeções futuras de chuvas acumuladas para 10, 15, 20, 25, 30, 60, 360, 480, 600, 720 e 1.440 minutos; 1, 2, 3, 4, 5, 6 e 7 dias, com tempos de retorno de 2, 5, 10, 25, 50, 100 e 200 anos. Para cada ponto de grade e para cada estação, serão utilizadas as séries futuras de máximos anuais corrigidas de viés (particularmente para a duração de 24 h), conforme descritos na meta 6. Para atualizar, via modelo estatístico bayesiano, os parâmetros de localização e escala das distribuições de extremos sob clima futuro, condicionando o parâmetro de forma às distribuições históricas estimadas. Em seguida, essas estimativas futuras de 24 h serão propagadas para as demais durações por meio das relações de escala entre durações, obtendo assim, para cada duração e para cada tempo de retorno, as intensidades projetadas em clima futuro e permitindo a comparação direta entre períodos histórico e futuro em cada célula da grade.

Os ajustes às distribuições extremas e os ajustes às equações IDF aplicados serão os mesmo dos dados históricos conforme descrito na meta 9 o procedimento de correção de viés adotado para as projeções será avaliado dentre as alternativas descritas e analisadas na meta 6.

A metodologia utilizada para a seleção dos modelos climáticos será definida com base na literatura científica. Ainda não há uma formulação operacional consolidada para esta atividade, tendo em vista que, na maioria dos estudos, essa análise é conduzida na perspectiva de disponibilidade hídrica e não de extremos. Uma das alternativas é o trabalho de Silva [-@Silva.2025]. O procedimento de seleção dos modelos climáticos globais (MCGs) foi realizado tratando a precipitação observada em cada estação como variável resposta e as estimativas dos 35 MCGs como preditores. Para cada estação, inicialmente avaliou-se a importância relativa de cada MCG aplicando sete métricas de relevância (RIMs), que atribuem peso a cada modelo considerando sua contribuição estatística e mitigando problemas como colinearidade. Em seguida, essas sete métricas foram combinadas em um índice síntese único (CPI), que permite comparar diretamente o desempenho dos modelos em cada estação. Depois, os valores do CPI foram agrupados por similaridade de desempenho usando um método de classificação (JOM), produzindo classes de qualidade para os MCGs em cada estação. Por fim, verificou-se, entre todas as estações, quais modelos pertenciam com maior frequência à melhor classe do JOM; esses modelos, mais consistentemente bem ranqueados, foram selecionados para compor o ensemble climático utilizado nas projeções.

Os resultados desta etapa metodológica serão disponibilizados a partir de scripts do R ou Python, um relatório com a descrição do processo de obtenção das IDFs para o clima futuro nos pontos de grade, relatório com as IDFs para o clima futuro nas estações pluviométricas/pluviográficas, relatório com análise de seleção dos modelos climáticos mais representativos, a base de dados com as IDFs projetadas nos pontos de grade para o clima futuro.

::: {#refs}
:::