---
title: "Análise da estrutura temporal das intensidades máximas anuais"
date: last-modified
date-format: "DD/MM/YYYY HH:mm:ss"
bibliography: referencias/ref_desagregacao.bib
---

## Análise da hipótese de invariância de escala

Originalmente, temos a seguinte relação para a invariância simples de escala [@Nguyen.1998]:

$$
f(\lambda x) = C(\lambda)f(x)
$$

A expressão acima relaciona uma função $f(x)$ a uma função escalonada $f(\lambda x)$ através de um coeficiente $C(\lambda)$, este igual a $\lambda^{-H}$ no caso simples. O fator de escalonamento, por sua vez, é dado por $\lambda = d/D$, sendo $D$ o valor não escalonado (ex. 24 h) e $d = \lambda D$. Através da relação de invariância de escala temporal, as intensidades para durações diferentes seguem a relação [@Menabde.1999]:

$$
I_d \overset{d}{=}\left( \frac{d}{D} \right)^{-H} I_D,
$$ {#eq-invariancia-escala-menabde}

ou seja, sendo iguais em distribuição à exceção de um fator de escala. Essa relação também pode ser expandida para momentos de ordem $q$:

$$
E[I_d^q] = \left(\frac{d}{D}\right)^{-Hq} E[I_D^q],
$$ que pode ser reescrita como:

$$
\begin{gather}
E[I_d^q] = \frac{D^{Hq}}{d^{Hq}} E[I_D^q] \\
E[I_d^q] = d^{-Hq} \ D^{Hq} \ E[I_D^q].
\end{gather}
$$ Como $H$ e $D$ são escalares constantes, podemos chamar $f(q) = D^{Hq} \ E[I_D^q]$ e, assim, obter:

$$
E[I_d^q] = f(q) \ d^{-Hq}
$$ {#eq-invariancia-reduzida}

Em um procedimento de regressão linear com duas variáveis (uma dependente $Y$ e outra independente $X$), podemos estabelecer uma relação do tipo $Y = \beta_0 + \beta_1 X$. Se tirarmos o logaritmo de @eq-invariancia-reduzida, conseguimos manipular a expressão para tomar a forma de uma relação linear:

$$
\log(E[I_d^q]) = \log{\left[ f(q) \ d^{-Hq} \right]} = \log(f(q)) + (-Hq)\log(d),
$$

em que a variável dependente $Y = \log(E[I_d^q])$ será função de uma variável independente $\log(d)$ multiplicada por um parâmetro $\beta_1 = -Hq$, somada a um parâmetro médio $\beta_0 = \log(f(q))$, o qual será constante se definirmos a ordem dos momentos não centrais $q = 1, 2$.

A hipótese de invariância de escala pode ser avaliada regionalmente, agrupando todos os anos de todas as estações do conjunto para uma mesma duração $d$ e ajustando um modelo ded regresão linear. Para o 1º e 2º momentos não centrais (ou seja, $q = 1$ e $q = 2$ respectivamente) teremos

$$
\begin{align}
q=1: & \quad \beta_0 = f(q = 1) = D^{H} \times E[I_d] \\
q=2:& \quad \beta_0 = f(q = 2) = D^{2H} \times E[I_d^2], \\
\end{align}
$$

e assim

$$
\begin{align}
q=1: & \quad \log(E[I_d]) = \log(f(1)) + (-H)\log(d) \\
q=2: & \quad \log(E[I_d^2]) = \log(f(2)) + (-2H)\log(d).
\end{align}
$$

Ajustando o valor do coeficiente angular $\beta_1$, teremos $\beta_1 = H_1 =  -H$ para o primeiro momento não central e $\beta_1 = H_2 = -2H$ para o segundo momento não central e, em teoria, $H_1 \approx H_2/2$.

## Coeficientes de desagregação

Há no Brasil um histórico de utilização de coeficientes de desagregação entre lâminas de precipitação de diferentes durações (citar CETESB). Estes coeficientes ($C_P$) são determinados a partir do ajuste de uma distribuição de probabilidade de eventos extremos às séries de máximos anuais de uma duração conhecida (usualmente de estações convencionais, ou seja, precipitações diárias $P_D$). Em suma:

$$
C_P = \frac{P_d}{P_D}
$$

Estes coeficientes convencionais podem ser relacionados com a invariância de escala de intensidades de chuva. Sendo $I_d = P_d \times d$, $C_P$ será:

$$
C_P = \frac{P_d}{P_D} = \frac{I_d \times d}{I_D \times D} = \frac{I_d}{I_D} \times \frac{d}{D}
$$

O coeficiente de desagregação temporal das intensidades ($C_I$), seguindo a expressão em @eq-invariancia-escala-menabde, será:

$$
C_I = \frac{I_d}{I_D} = \left( \frac{d}{D} \right)^{-H}
$$

Assim, a partir da definição do parâmetro de escala $H$ pela regressão linear acima, é possível relacionar $C_P$ e $C_I$ como:

$$
\begin{align}
C_P & = \frac{I_d}{I_D} \times \left( \frac{d}{D} \right) = C_I \times \left( \frac{d}{D} \right) \\
& = \left( \frac{d}{D} \right)^{-H} \times \left( \frac{d}{D} \right),
\end{align}
$$

e, finalmente,

$$
C_P = \left( \frac{d}{D} \right)^{-H + 1}
$$ {#eq-coef-desagregacao}
