---
title: "Sensoriamento Remoto"
date: now
date-format: long
bibliography: referencias/refs_sensoriamento_remoto.bib
---

::: {style="text-align: justify;"}
A ausência de redes locais de precipitação observada dificulta o desenvolvimento de curvas IDF [@Lanciotti.2022]. Em casos como esse, a busca por fontes alternativas de dados para construção dessas curvas se torna necessária, busca essa que motivou a evolução de produto derivados de sensoriamento remoto (SSPs) com alta resolução temporal e espacial com cobertura quase global [@Islam.2022]. Diferentes tipos de séries climáticas remotas e combinadas são usadas para estimar IDFs, incluindo produtos como TRMM (*Tropical Rainfall Measuring Mission*), GPM (*Global Precipitation Measurement*), GSMaP (*Global Satellite Mapping of Precipitation*), PERSIANN (*Precipitation Estimation from Remotely Sensed Information Using Artifitial Neural Networks*) e CHIRPS (*Climate Hazards Group InfraRed Precipitation with Station Data*). Esses SSPs possuem grande importância para regiões onde a rede de estações é de baixa resolução temporal e densidade espacial [@Islam.2022; @Wright.2017].

Apesar de se apresentarem como uma alternativa promissora no contexto acima, esses produtos possuem incertezas e erros associados decorrentes da topografia, erros na observação em razão vento, evaporação e também em decorrência da diferença entre a escala da resolução espacial do SSP e das observações locais, o que torna difícil aplicações completamente operacionais [@Islam.2022; @Lanciotti.2022; @Dehaghani.2023; @Baig.2023].

O objetivo deste capítulo é introduzir alguns dos principais produtos de sensoriamento remoto de precipitação disponíveis e utilizados na atualidade. Uma das definições da técnica diz respeito à sua forma de obtenção: remota. Isso significa que não há contato entre o sensor e o objeto de interesse. Para precipitação, diferentes abordagens podem ser utilizadas e diferentes formas de processamento que compõem bases de dados variadas em alta resolução temporal de pluviosidade oriundas de reanálises integradas, sensores de satélites e combinações com dados terrestres [@Papa.2025]. Serão apresentados a seguir métodos de obtenção e a aplicação de diferentes produtos de sensoriamento remoto na construção de curvas IDF.

## Radar {#sec-radar}

Radares meteorológicos são capazes de calcular precipitação média em uma área relativamente grande, ao contrário de medidores pontuais [@Lanciotti.2022], emitindo ondas eletromagnéticas que retroespalham ao interagir com hidrometeoros de chuva e retornam ao sensor. Dessa informação que retorna são extraídas informações sobre localização, intensidade, movimento da precipitação e a detecção de tempestades individuais [@Marra.2015], normalmente com uma resolução espacial de 1 km × 1 km e resolução temporal subdiária e diária [@Sivasubramaniam.2019].

O estudo de @Overeem.2009 é amplamente reconhecido como um dos pioneiros na estimativa de curvas IDF com sensoriamento remoto na Holanda utilizando radares meteorológicos. O trabalho utilizou registros ao longo de 11 anos e durações variadas (15 min a 24 h), possibilitando identificar a existência de uma concordância razoável entre os parâmetros da distribuição Generalizada de Valores Extremos obtidos de pluviômetros e de estimativas de radar. Para durações mais longas (p.ex. 24 h), porém, os autores constataram que o comprimento da série temporal com os radares foi relativamente curto para o ajuste da GEV.

@Peleg.2018 realizaram um estudo para qualificar a variabilidade do subpixel de radar meteorológico utilizando o modelo STREAP (*Spact-Time Realizations of A real Precipitation*), buscando reduzir a escala da precipitação de radar registrada em um determinado pixel. A análise se deu utilizando dados de um único pixel (1,4° × 1 km) de um radar de banda C com dados de 1990-2013 em uma área com alta de densidade de pluviômetros. Curvas IDF foram construídas utilizando a GEV e os autores relatam que estimativas de radar subestimam as precipitações extremas em grande parte dos subpixels e que em períodos de retorno mais longos com durações curtas a variabilidade é maior. Além disso, a incerteza no cálculo da variabilidade do subpixel aumenta quando se leva em consideração a variabilidade climática natural.

Alguns produtos disponíveis utilizam empregam tanto dados de observação local em conjunto de estimativas de radar, combinando tanto maior precisão como uma maior cobertura espacial. O trabalho de @Haruna.2024 utilizam produtos o *CombiPrecip* (CPC), disponível na Suíça, o qual combina dados observados com um conjunto de cinco radares Doppler de banda C. As estimativas do SSP foram utilizadas para derivar curvas IDAF (que combina também área) a partir do ajuste da distribuição Generalizada de Pareto Estendida. Incertezas foram calculadas com método *bootstrap* e estimativas para diferentes períodos de retorno foram semelhantes ao comparar pixel-ponto CombiPrecip com observações locais. Os autores chamam a atenção, porém, para a curta duração das séries do CPC.

Apesar de bons resultados quando combinado com observações locais, há também complicações operacionais, como análises em uma escala maior, em razão do alcance limitado e alto custo [@Yu.2022]. Satélites, porém, fornecem um monitoramento em uma boa resolução espacial e temporal, em diferentes pontos geográficos e em altas altitudes [@Tang.2021].

## Satélite {#sec-satelite}

Diferentes missões foram lançadas específicas para precipitação. TRMM (mencionado anteriormente) foi um projeto multissatélite lançado em 1997 com o intuito de apromirar a qualidade ddas estimativas de precipitação para aplicação em pesquisas em meteorologia e hirologia [@Pedreira.2021]. Foi importante para previsão e análise de precipitação, utilizando sensores que possibilitavam a avaliação de nuvens, chuva, fluxo de calor, raios e outros aspectos relevantes para o ciclo da água combinando dados obtidos por três sensores: Radar de Precipitação, Gerador de Imagens de Micro-ondas e Sensor Visível e Infravermelho [@Liu.2012]. Uma vantagem dos produtos TRMM são os fornecimentos de frequência, duração e intensidade nas regiões tropicais, sendo avaliados na Índia [@Shukla.2019] e avaliados para construção de IDFs [@Noor.2021; @Zoysa.2023; @Zoysa.2024].

A missão GPM é considerada a sucessora do TRMM, desenvolvida também para precipitação e lançada em 2014 [@Arshad.2021]. O GPM emprega o algoritmo IMERG – *Integrated Multi-satellite Retrievals for GPM* – projetado para intercalar, mesclar e interpolar todas as estimativas de micro-ondas e infravermelho da rede de satélites GPM com observações e outros auxiliadores [@Huffman.2020; @Aksu.2023]. Seus produtos são usados em trabalhos como os de @Islam.2022 e @Venkatesh.2022 para derivar curvas IDF, combinando os produtos com observações locais.

Outros produtos também estão disponíveis que são de interesse para análise de extremos de precipitação utilizando sensoriamento remoto. O CHIRPS consiste em um banco de dados disponível desde 1981 até a atualidade, mas com diferentes passos de tempo e resoluções espaciais [@Musie.2019]. Sua construção envolve múltiplos conjuntos de dados que incluem o campo de precipitação da segunda versão do Modelo Atmosférico do Sistema de Previsão Climática da NOAA (CFSv2), dados do TRMM-3B42V7, informações de climatologia mensal de precipitação (CHPclim) e dados de estações pluviométricas [@Duan.2016], entregues em resoluções espaciais de 0,05° e 0,25°. @Alsumaiti.2023 utilizam dados do CHIRPS para atualizar curvas IDF de alta resolução temporal nos Emirados Árabes Unidos. Mais recentemente, ainda, @Attar.2025 usando estimativas do CHIRPS para derivar curvas IDF e construir hietográficos de chuva para 24 bacias hidrográficas no sudeste asiático.

O GSMaP é um produto de precipitação multissatélite desenvolvido a partir da combinação de observações de micro-ondas e infravermelho, o que lhe confere alta resolução temporal e espacial [@Kubota.2007]. O GSMaP fornece três versões dos seus produtos, nas quais são: produtos de quase tempo real (GSMaP_N), produtos padrão (GSMaP_M) e produtos padrão calibrados por medidores (GSMaP_G). Nos seus produtos padrões as estimativas de precipitação são geradas em três etapas: 1) recuperar as taxas de precipitação a partir de dados de micro-ondas passivos (PMW); 2) propagar os pixels de chuva utilizando vetores de movimento atmosférico em processos de interpolação para frente e para trás; e 3) refinar os dados com base na temperatura de brilho infravermelho (IR) e nas taxas de precipitação da superfície [@Zhou.2020]. GSMaP foi usado por @Sun.2019, integrado com um pulsos retangulares de Bartlett-Lewis, para desagregar observações diárias locais e derivar curvas IDF mais confiáveis, enquanto Noor et al. 2022 usam o SSP para construir curvas IDF para locais sem medição local sob cenários de mudança climática, aplicando a metodologia para a Malásia Peninsular.

O PERSIANN foi desenvolvido nas últimas décadas pelo Centro de Hidrometeorologia e Sensoriamento Remoto (CHRS), da Universidade da Califórnia, Irvine, colaborando com a NASA, NOAA e o programa da UNESCO para a Rede Global de Informação sobre Água e Desenvolvimento para Terras Áridas [@Baig.2023]. A estimativa da precipitação é realizada a partir de informações de sensores remotos utilizando redes neurais artificiais [@Ella.2024]. Atualmente, a família PERSIANN inclui cinco produtos diferentes, sendo eles o PERSIANN, PERSIANN-Cloud Classification System, PERSIANN-Climate Data Record, PERSIANN-CCS-CDR e PERSIANN-Dynamic Infrared Rain Rate. Vale ressaltar que, os produtos da família PERSIANN possuem diferentes algoritmos e resoluções espaço-temporais, podendo variar de 0.04º x 0.04º a 0.25º x 0.25º em um período de 1 a 3 horas [@Huang.2021]. @Baig.2023 avaliaram o desempenho do PERSIANN, PERSIANN-CCS, PERSIANN-CDR e PDIR-Now na construção de curvas IDF, considerando os dados diários de precipitação, com o intuito de compreender as semelhanças, intercomparação e variações entre esses produtos.

Em meio à variedade de produtos, algoritmos diferentes, formas diferentes de combinar dados observacionais, um número de trabalhos se dedica a avaliar a performance desses SSPs comparativamente para construção de curvas IDF. @Mtibaa.2024 comparou IDFs construídas de conjunto de dados de precipitação dados observados, radares meteorológicos (R/A) e observações de satélite (IMERG_G, GsMAP_G e CMORPH_G), onde utilizou-se a abordagem de pixel a ponto para avaliar as estatísticas derivadas dos dados de sensoriamento remoto (ou seja, parâmetros GEV e IDFs). Foi observado que o conjunto de dados de R/A obtiveram melhor desempenho para extremos de chuva de uma hora, especialmente nas regiões frias com verões quentes, entretanto, o IMERG_G apresentou desempenho mais alto para precipitações extremas de longas durações, superando os outros SSPs. @Ella.2024 realizaram a comparação dos produtos PERSIANN (PERSIANN, PERSIANN-CCS, PERSIANN-CDR e PDIR-Now) com conjuntos de dados NASA-POWER em comparação com o máximo anual disponível de precipitação de observação diária, tendo como critério a comparação de análise de características de precipitação, análise de frequência e desenvolvimento de curvas IDF. Com base nos resultados, o PERSIANN-CDR apresentou ser o mais apropriado seguindo os critérios de comparação das medidas de erro RMSE, Bias, CC e R2. @Mianabadi.2023, utilizou os produtos MSWEP, CHIRPS, PERSIANN-CDR e PERSIANN-CCS-CDR, com o intuito de avaliar o desempenho de cada sensor no desenvolvimento de curvas IDF para precipitação diária. A avaliação contou com 14 estações meteorológicas sob diferentes condições climáticas. Diante as métricas de avaliação (EM, RMSE, PCC e RE), o CHIRPS apresentou melhor desempenho do que os outros produtos para todos os períodos de retorno, já o PERSIANN-CSS-CDR teve o pior desempenho comparado aos produtos. Vale ressaltar que, a avaliação da qualidade dos SSPs pode ser influenciada de acordo com a distribuição e quantidade de pluviômetros [@Mtibaa.2024]
:::

## Referências

::: {#refs style="text-align: justify;"}
:::
